---
language: python
python: "{{ python_version_for_travis }}"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible=={{ ansible_version_for_travis }}

script:
- ansible-playbook -i roles/jenkins/tests/inventory roles/jenkins/tests/test.yml --syntax-check